language: php
php:
  - 7.4.5
  
before_script:
  - composer install

    
notifications:
  slack:
    on_success: always
  email:
    recipients:
      - 11700274@pxl.student.be
      - semih.sahin@pxl.student.be
    on_success: always # default: change
    on_failure: always # default: always
  

